Traceback (most recent call last):
  File "/Users/jue/opt/anaconda3/envs/mybook/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/jue/opt/anaconda3/envs/mybook/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/jue/opt/anaconda3/envs/mybook/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/jue/opt/anaconda3/envs/mybook/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/jue/opt/anaconda3/envs/mybook/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/jue/opt/anaconda3/envs/mybook/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/jue/opt/anaconda3/envs/mybook/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/jue/opt/anaconda3/envs/mybook/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy
# from pylab import plot, show, grid, xlabel, ylabel
import matplotlib as mpl
mpl.rcParams['figure.dpi'] = 400
import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

# The Wiener process parameter.
delta = 2
# Total time.
T = 10.0
# Number of steps.
N = 500
# Time step size
dt = T/N
# Number of realizations to generate.
m = 20
# Create an empty array to store the realizations.
x = numpy.empty((m,N+1))
# Initial values of x.
x[:, 0] = 50

brownian(x[:,0], N, dt, delta, out=x[:,1:])

t = numpy.linspace(0.0, N*dt, N+1)
fig, ax = plt.subplots(figsize=(6, 4))
for k in range(m):
    ax.plot(t, x[k])
ax.set_xlabel('t')
ax.set_ylabel('x')
# xlabel('t', fontsize=16)
# ylabel('x', fontsize=16)
grid(True)
show()
# fig.savefig('brownian_motion_1d.pdf', transparent=True, dpi=400)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 34[0m
[1;32m     31[0m ax[38;5;241m.[39mset_ylabel([38;5;124m'[39m[38;5;124mx[39m[38;5;124m'[39m)
[1;32m     32[0m [38;5;66;03m# xlabel('t', fontsize=16)[39;00m
[1;32m     33[0m [38;5;66;03m# ylabel('x', fontsize=16)[39;00m
[0;32m---> 34[0m [43mgrid[49m([38;5;28;01mTrue[39;00m)
[1;32m     35[0m show()
[1;32m     36[0m [38;5;66;03m# fig.savefig('brownian_motion_1d.pdf', transparent=True, dpi=400)[39;00m

[0;31mNameError[0m: name 'grid' is not defined
NameError: name 'grid' is not defined

